# Generated by Django 3.2.5 on 2023-03-10 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_pdf_library'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdf_library',
            old_name='picture',
            new_name='file',
        ),
    ]
