# Generated by Django 3.2.5 on 2023-03-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_quizehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizehistory',
            name='line',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
