# Generated by Django 3.2.5 on 2023-03-17 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_page_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page_comment',
            old_name='commment',
            new_name='comment',
        ),
    ]
