# Generated by Django 3.2.5 on 2023-03-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_commment_page_comment_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='side_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
    ]
