# Generated by Django 3.2.5 on 2023-03-17 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_side_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='the_content',
            name='as_sidepage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.side_page'),
        ),
    ]
