# Generated by Django 3.2.5 on 2023-03-29 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_about_page'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='about_page',
            new_name='about_page_table',
        ),
    ]
